//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecourbis.FormularioNFRemRet.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DADOSADVEntities : DbContext
    {
        public DADOSADVEntities()
            : base("name=DADOSADVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PAG010> PAG010 { get; set; }
        public DbSet<PAH010> PAH010 { get; set; }
        public DbSet<PAI010> PAI010 { get; set; }
        public DbSet<viewForne> viewForne { get; set; }
        public DbSet<viewFuncao> viewFuncao { get; set; }
        public DbSet<viewProd> viewProd { get; set; }
        public DbSet<viewUnidMed> viewUnidMed { get; set; }
        public DbSet<viewGstEco> viewGstEco { get; set; }
        public DbSet<viewMatUser> viewMatUser { get; set; }
    }
}
