//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecourbis.FormularioNFRemRet.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAG010
    {
        public string PAG_FILIAL { get; set; }
        public double PAG_COD { get; set; }
        public string D_E_L_E_T_ { get; set; }
        public int R_E_C_N_O_ { get; set; }
    }
}
