//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecourbis.FormularioNFRemRet.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAH010
    {
        public string PAH_FILIAL { get; set; }
        public double PAH_CONTRO { get; set; }
        public string PAH_RETIRA { get; set; }
        public string PAH_USER { get; set; }
        public string PAH_NUMUSE { get; set; }
        public string PAH_DEPUSE { get; set; }
        public string PAH_EMAIL { get; set; }
        public string PAH_DTSOLI { get; set; }
        public string PAH_PRAZO { get; set; }
        public string PAH_PRAZOU { get; set; }
        public string PAH_PRAZOS { get; set; }
        public string PAH_UNIDAD { get; set; }
        public string PAH_TIPO { get; set; }
        public string PAH_NFORI { get; set; }
        public string PAH_CLIFOR { get; set; }
        public string PAH_LOJA { get; set; }
        public string PAH_NOME { get; set; }
        public string PAH_END { get; set; }
        public string PAH_TEL { get; set; }
        public string PAH_NFREM { get; set; }
        public string PAH_NFTERC { get; set; }
        public string PAH_NFRET { get; set; }
        public string PAH_JUST { get; set; }
        public string PAH_FUNUSE { get; set; }
        public string PAH_CGC { get; set; }
        public string PAH_EMAILF { get; set; }
        public string PAH_BAIXAD { get; set; }
        public string D_E_L_E_T_ { get; set; }
        public int R_E_C_N_O_ { get; set; }
    }
}
