//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecourbis.FormularioNFRemRet.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAI010
    {
        public string PAI_FILIAL { get; set; }
        public double PAI_ITEM { get; set; }
        public string PAI_CODP { get; set; }
        public string PAI_DESC { get; set; }
        public string PAI_QTD { get; set; }
        public string PAI_CONTRO { get; set; }
        public string PAI_PRAZO { get; set; }
        public string PAI_UNMED { get; set; }
        public double PAI_LOGPRA { get; set; }
        public string D_E_L_E_T_ { get; set; }
        public int R_E_C_N_O_ { get; set; }
    }
}
