//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecourbis.FormularioNFRemRet.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewForne
    {
        public string A2_COD { get; set; }
        public string A2_NOME { get; set; }
        public string A2_LOJA { get; set; }
        public string A2_END { get; set; }
        public string A2_DDD { get; set; }
        public string A2_TEL { get; set; }
        public string A2_EMAIL { get; set; }
        public string A2_CGC { get; set; }
    }
}
