//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecourbis.FormularioNFRemRet.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewUnidMed
    {
        public string AH_UNIMED { get; set; }
        public string AH_UMRES { get; set; }
    }
}
