//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecourbis.FormularioNFRemRet.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewGstEco
    {
        public string Nome { get; set; }
        public Nullable<int> Matricula { get; set; }
        public string CC { get; set; }
        public string Custo { get; set; }
        public string CodGestor { get; set; }
        public Nullable<int> Superior { get; set; }
        public string NomeSuperior { get; set; }
        public int R_E_C_N_O_ { get; set; }
    }
}
