//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Ecourbis.FormularioNFRemRet.Business.br.com.ecourbis.webservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSusernameSoap", Namespace="http://webservice.ecourbis.com.br/")]
    public partial class WSusername : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback dataset_SAMAccountNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback dataset_auditoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback dataset_ManagersOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsManagerNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback dataset_UsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback ArrayList_OfficialsMicrosigaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ArrayList_activedirectoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsSAMAccountNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsFullNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsDepartmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsEmailRequestorOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsCompanyOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsContainerOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsBiometricoOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsAnalistaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSusername() {
            this.Url = global::Ecourbis.FormularioNFRemRet.Business.Properties.Settings.Default.Ecourbis_FormularioNFRemRet_Business_br_com_ecourbis_webservice_WSusername;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event dataset_SAMAccountNameCompletedEventHandler dataset_SAMAccountNameCompleted;
        
        /// <remarks/>
        public event dataset_auditoriaCompletedEventHandler dataset_auditoriaCompleted;
        
        /// <remarks/>
        public event dataset_ManagersCompletedEventHandler dataset_ManagersCompleted;
        
        /// <remarks/>
        public event wsManagerNameCompletedEventHandler wsManagerNameCompleted;
        
        /// <remarks/>
        public event dataset_UsersCompletedEventHandler dataset_UsersCompleted;
        
        /// <remarks/>
        public event ArrayList_OfficialsMicrosigaCompletedEventHandler ArrayList_OfficialsMicrosigaCompleted;
        
        /// <remarks/>
        public event ArrayList_activedirectoryCompletedEventHandler ArrayList_activedirectoryCompleted;
        
        /// <remarks/>
        public event wsSAMAccountNameCompletedEventHandler wsSAMAccountNameCompleted;
        
        /// <remarks/>
        public event wsFullNameCompletedEventHandler wsFullNameCompleted;
        
        /// <remarks/>
        public event wsDepartmentCompletedEventHandler wsDepartmentCompleted;
        
        /// <remarks/>
        public event wsEmailRequestorCompletedEventHandler wsEmailRequestorCompleted;
        
        /// <remarks/>
        public event wsCompanyCompletedEventHandler wsCompanyCompleted;
        
        /// <remarks/>
        public event wsContainerCompletedEventHandler wsContainerCompleted;
        
        /// <remarks/>
        public event wsBiometricoCompletedEventHandler wsBiometricoCompleted;
        
        /// <remarks/>
        public event wsAnalistaCompletedEventHandler wsAnalistaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.ecourbis.com.br/dataset_SAMAccountName", RequestNamespace="http://webservice.ecourbis.com.br/", ResponseNamespace="http://webservice.ecourbis.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet dataset_SAMAccountName(string sSAMAccountName) {
            object[] results = this.Invoke("dataset_SAMAccountName", new object[] {
                        sSAMAccountName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void dataset_SAMAccountNameAsync(string sSAMAccountName) {
            this.dataset_SAMAccountNameAsync(sSAMAccountName, null);
        }
        
        /// <remarks/>
        public void dataset_SAMAccountNameAsync(string sSAMAccountName, object userState) {
            if ((this.dataset_SAMAccountNameOperationCompleted == null)) {
                this.dataset_SAMAccountNameOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondataset_SAMAccountNameOperationCompleted);
            }
            this.InvokeAsync("dataset_SAMAccountName", new object[] {
                        sSAMAccountName}, this.dataset_SAMAccountNameOperationCompleted, userState);
        }
        
        private void Ondataset_SAMAccountNameOperationCompleted(object arg) {
            if ((this.dataset_SAMAccountNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dataset_SAMAccountNameCompleted(this, new dataset_SAMAccountNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.ecourbis.com.br/dataset_auditoria", RequestNamespace="http://webservice.ecourbis.com.br/", ResponseNamespace="http://webservice.ecourbis.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet dataset_auditoria() {
            object[] results = this.Invoke("dataset_auditoria", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void dataset_auditoriaAsync() {
            this.dataset_auditoriaAsync(null);
        }
        
        /// <remarks/>
        public void dataset_auditoriaAsync(object userState) {
            if ((this.dataset_auditoriaOperationCompleted == null)) {
                this.dataset_auditoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondataset_auditoriaOperationCompleted);
            }
            this.InvokeAsync("dataset_auditoria", new object[0], this.dataset_auditoriaOperationCompleted, userState);
        }
        
        private void Ondataset_auditoriaOperationCompleted(object arg) {
            if ((this.dataset_auditoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dataset_auditoriaCompleted(this, new dataset_auditoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.ecourbis.com.br/dataset_Managers", RequestNamespace="http://webservice.ecourbis.com.br/", ResponseNamespace="http://webservice.ecourbis.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet dataset_Managers() {
            object[] results = this.Invoke("dataset_Managers", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void dataset_ManagersAsync() {
            this.dataset_ManagersAsync(null);
        }
        
        /// <remarks/>
        public void dataset_ManagersAsync(object userState) {
            if ((this.dataset_ManagersOperationCompleted == null)) {
                this.dataset_ManagersOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondataset_ManagersOperationCompleted);
            }
            this.InvokeAsync("dataset_Managers", new object[0], this.dataset_ManagersOperationCompleted, userState);
        }
        
        private void Ondataset_ManagersOperationCompleted(object arg) {
            if ((this.dataset_ManagersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dataset_ManagersCompleted(this, new dataset_ManagersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.ecourbis.com.br/wsManagerName", RequestNamespace="http://webservice.ecourbis.com.br/", ResponseNamespace="http://webservice.ecourbis.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wsManagerName(string sDepartamento) {
            object[] results = this.Invoke("wsManagerName", new object[] {
                        sDepartamento});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsManagerNameAsync(string sDepartamento) {
            this.wsManagerNameAsync(sDepartamento, null);
        }
        
        /// <remarks/>
        public void wsManagerNameAsync(string sDepartamento, object userState) {
            if ((this.wsManagerNameOperationCompleted == null)) {
                this.wsManagerNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsManagerNameOperationCompleted);
            }
            this.InvokeAsync("wsManagerName", new object[] {
                        sDepartamento}, this.wsManagerNameOperationCompleted, userState);
        }
        
        private void OnwsManagerNameOperationCompleted(object arg) {
            if ((this.wsManagerNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsManagerNameCompleted(this, new wsManagerNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.ecourbis.com.br/dataset_Users", RequestNamespace="http://webservice.ecourbis.com.br/", ResponseNamespace="http://webservice.ecourbis.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet dataset_Users() {
            object[] results = this.Invoke("dataset_Users", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void dataset_UsersAsync() {
            this.dataset_UsersAsync(null);
        }
        
        /// <remarks/>
        public void dataset_UsersAsync(object userState) {
            if ((this.dataset_UsersOperationCompleted == null)) {
                this.dataset_UsersOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondataset_UsersOperationCompleted);
            }
            this.InvokeAsync("dataset_Users", new object[0], this.dataset_UsersOperationCompleted, userState);
        }
        
        private void Ondataset_UsersOperationCompleted(object arg) {
            if ((this.dataset_UsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dataset_UsersCompleted(this, new dataset_UsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.ecourbis.com.br/ArrayList_OfficialsMicrosiga", RequestNamespace="http://webservice.ecourbis.com.br/", ResponseNamespace="http://webservice.ecourbis.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ArrayList_OfficialsMicrosiga(string sPrefixText) {
            object[] results = this.Invoke("ArrayList_OfficialsMicrosiga", new object[] {
                        sPrefixText});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ArrayList_OfficialsMicrosigaAsync(string sPrefixText) {
            this.ArrayList_OfficialsMicrosigaAsync(sPrefixText, null);
        }
        
        /// <remarks/>
        public void ArrayList_OfficialsMicrosigaAsync(string sPrefixText, object userState) {
            if ((this.ArrayList_OfficialsMicrosigaOperationCompleted == null)) {
                this.ArrayList_OfficialsMicrosigaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnArrayList_OfficialsMicrosigaOperationCompleted);
            }
            this.InvokeAsync("ArrayList_OfficialsMicrosiga", new object[] {
                        sPrefixText}, this.ArrayList_OfficialsMicrosigaOperationCompleted, userState);
        }
        
        private void OnArrayList_OfficialsMicrosigaOperationCompleted(object arg) {
            if ((this.ArrayList_OfficialsMicrosigaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ArrayList_OfficialsMicrosigaCompleted(this, new ArrayList_OfficialsMicrosigaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.ecourbis.com.br/ArrayList_activedirectory", RequestNamespace="http://webservice.ecourbis.com.br/", ResponseNamespace="http://webservice.ecourbis.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ArrayList_activedirectory(string sPrefixText) {
            object[] results = this.Invoke("ArrayList_activedirectory", new object[] {
                        sPrefixText});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ArrayList_activedirectoryAsync(string sPrefixText) {
            this.ArrayList_activedirectoryAsync(sPrefixText, null);
        }
        
        /// <remarks/>
        public void ArrayList_activedirectoryAsync(string sPrefixText, object userState) {
            if ((this.ArrayList_activedirectoryOperationCompleted == null)) {
                this.ArrayList_activedirectoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnArrayList_activedirectoryOperationCompleted);
            }
            this.InvokeAsync("ArrayList_activedirectory", new object[] {
                        sPrefixText}, this.ArrayList_activedirectoryOperationCompleted, userState);
        }
        
        private void OnArrayList_activedirectoryOperationCompleted(object arg) {
            if ((this.ArrayList_activedirectoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ArrayList_activedirectoryCompleted(this, new ArrayList_activedirectoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.ecourbis.com.br/wsSAMAccountName", RequestNamespace="http://webservice.ecourbis.com.br/", ResponseNamespace="http://webservice.ecourbis.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wsSAMAccountName(string sSAMAccountName) {
            object[] results = this.Invoke("wsSAMAccountName", new object[] {
                        sSAMAccountName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsSAMAccountNameAsync(string sSAMAccountName) {
            this.wsSAMAccountNameAsync(sSAMAccountName, null);
        }
        
        /// <remarks/>
        public void wsSAMAccountNameAsync(string sSAMAccountName, object userState) {
            if ((this.wsSAMAccountNameOperationCompleted == null)) {
                this.wsSAMAccountNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsSAMAccountNameOperationCompleted);
            }
            this.InvokeAsync("wsSAMAccountName", new object[] {
                        sSAMAccountName}, this.wsSAMAccountNameOperationCompleted, userState);
        }
        
        private void OnwsSAMAccountNameOperationCompleted(object arg) {
            if ((this.wsSAMAccountNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsSAMAccountNameCompleted(this, new wsSAMAccountNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.ecourbis.com.br/wsFullName", RequestNamespace="http://webservice.ecourbis.com.br/", ResponseNamespace="http://webservice.ecourbis.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wsFullName(string sSAMAccountName) {
            object[] results = this.Invoke("wsFullName", new object[] {
                        sSAMAccountName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsFullNameAsync(string sSAMAccountName) {
            this.wsFullNameAsync(sSAMAccountName, null);
        }
        
        /// <remarks/>
        public void wsFullNameAsync(string sSAMAccountName, object userState) {
            if ((this.wsFullNameOperationCompleted == null)) {
                this.wsFullNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsFullNameOperationCompleted);
            }
            this.InvokeAsync("wsFullName", new object[] {
                        sSAMAccountName}, this.wsFullNameOperationCompleted, userState);
        }
        
        private void OnwsFullNameOperationCompleted(object arg) {
            if ((this.wsFullNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsFullNameCompleted(this, new wsFullNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.ecourbis.com.br/wsDepartment", RequestNamespace="http://webservice.ecourbis.com.br/", ResponseNamespace="http://webservice.ecourbis.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wsDepartment(string sSAMAccountName) {
            object[] results = this.Invoke("wsDepartment", new object[] {
                        sSAMAccountName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsDepartmentAsync(string sSAMAccountName) {
            this.wsDepartmentAsync(sSAMAccountName, null);
        }
        
        /// <remarks/>
        public void wsDepartmentAsync(string sSAMAccountName, object userState) {
            if ((this.wsDepartmentOperationCompleted == null)) {
                this.wsDepartmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsDepartmentOperationCompleted);
            }
            this.InvokeAsync("wsDepartment", new object[] {
                        sSAMAccountName}, this.wsDepartmentOperationCompleted, userState);
        }
        
        private void OnwsDepartmentOperationCompleted(object arg) {
            if ((this.wsDepartmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsDepartmentCompleted(this, new wsDepartmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.ecourbis.com.br/wsEmailRequestor", RequestNamespace="http://webservice.ecourbis.com.br/", ResponseNamespace="http://webservice.ecourbis.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wsEmailRequestor(string sSAMAccountName) {
            object[] results = this.Invoke("wsEmailRequestor", new object[] {
                        sSAMAccountName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsEmailRequestorAsync(string sSAMAccountName) {
            this.wsEmailRequestorAsync(sSAMAccountName, null);
        }
        
        /// <remarks/>
        public void wsEmailRequestorAsync(string sSAMAccountName, object userState) {
            if ((this.wsEmailRequestorOperationCompleted == null)) {
                this.wsEmailRequestorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsEmailRequestorOperationCompleted);
            }
            this.InvokeAsync("wsEmailRequestor", new object[] {
                        sSAMAccountName}, this.wsEmailRequestorOperationCompleted, userState);
        }
        
        private void OnwsEmailRequestorOperationCompleted(object arg) {
            if ((this.wsEmailRequestorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsEmailRequestorCompleted(this, new wsEmailRequestorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.ecourbis.com.br/wsCompany", RequestNamespace="http://webservice.ecourbis.com.br/", ResponseNamespace="http://webservice.ecourbis.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wsCompany(string sSAMAccountName) {
            object[] results = this.Invoke("wsCompany", new object[] {
                        sSAMAccountName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsCompanyAsync(string sSAMAccountName) {
            this.wsCompanyAsync(sSAMAccountName, null);
        }
        
        /// <remarks/>
        public void wsCompanyAsync(string sSAMAccountName, object userState) {
            if ((this.wsCompanyOperationCompleted == null)) {
                this.wsCompanyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsCompanyOperationCompleted);
            }
            this.InvokeAsync("wsCompany", new object[] {
                        sSAMAccountName}, this.wsCompanyOperationCompleted, userState);
        }
        
        private void OnwsCompanyOperationCompleted(object arg) {
            if ((this.wsCompanyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsCompanyCompleted(this, new wsCompanyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.ecourbis.com.br/wsContainer", RequestNamespace="http://webservice.ecourbis.com.br/", ResponseNamespace="http://webservice.ecourbis.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wsContainer(string sSAMAccountName) {
            object[] results = this.Invoke("wsContainer", new object[] {
                        sSAMAccountName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsContainerAsync(string sSAMAccountName) {
            this.wsContainerAsync(sSAMAccountName, null);
        }
        
        /// <remarks/>
        public void wsContainerAsync(string sSAMAccountName, object userState) {
            if ((this.wsContainerOperationCompleted == null)) {
                this.wsContainerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsContainerOperationCompleted);
            }
            this.InvokeAsync("wsContainer", new object[] {
                        sSAMAccountName}, this.wsContainerOperationCompleted, userState);
        }
        
        private void OnwsContainerOperationCompleted(object arg) {
            if ((this.wsContainerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsContainerCompleted(this, new wsContainerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.ecourbis.com.br/wsBiometrico", RequestNamespace="http://webservice.ecourbis.com.br/", ResponseNamespace="http://webservice.ecourbis.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wsBiometrico(string sSAMAccountName) {
            object[] results = this.Invoke("wsBiometrico", new object[] {
                        sSAMAccountName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsBiometricoAsync(string sSAMAccountName) {
            this.wsBiometricoAsync(sSAMAccountName, null);
        }
        
        /// <remarks/>
        public void wsBiometricoAsync(string sSAMAccountName, object userState) {
            if ((this.wsBiometricoOperationCompleted == null)) {
                this.wsBiometricoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsBiometricoOperationCompleted);
            }
            this.InvokeAsync("wsBiometrico", new object[] {
                        sSAMAccountName}, this.wsBiometricoOperationCompleted, userState);
        }
        
        private void OnwsBiometricoOperationCompleted(object arg) {
            if ((this.wsBiometricoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsBiometricoCompleted(this, new wsBiometricoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.ecourbis.com.br/wsAnalista", RequestNamespace="http://webservice.ecourbis.com.br/", ResponseNamespace="http://webservice.ecourbis.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wsAnalista(string sSAMAccountName) {
            object[] results = this.Invoke("wsAnalista", new object[] {
                        sSAMAccountName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsAnalistaAsync(string sSAMAccountName) {
            this.wsAnalistaAsync(sSAMAccountName, null);
        }
        
        /// <remarks/>
        public void wsAnalistaAsync(string sSAMAccountName, object userState) {
            if ((this.wsAnalistaOperationCompleted == null)) {
                this.wsAnalistaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsAnalistaOperationCompleted);
            }
            this.InvokeAsync("wsAnalista", new object[] {
                        sSAMAccountName}, this.wsAnalistaOperationCompleted, userState);
        }
        
        private void OnwsAnalistaOperationCompleted(object arg) {
            if ((this.wsAnalistaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsAnalistaCompleted(this, new wsAnalistaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void dataset_SAMAccountNameCompletedEventHandler(object sender, dataset_SAMAccountNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dataset_SAMAccountNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dataset_SAMAccountNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void dataset_auditoriaCompletedEventHandler(object sender, dataset_auditoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dataset_auditoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dataset_auditoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void dataset_ManagersCompletedEventHandler(object sender, dataset_ManagersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dataset_ManagersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dataset_ManagersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void wsManagerNameCompletedEventHandler(object sender, wsManagerNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsManagerNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsManagerNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void dataset_UsersCompletedEventHandler(object sender, dataset_UsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dataset_UsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dataset_UsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ArrayList_OfficialsMicrosigaCompletedEventHandler(object sender, ArrayList_OfficialsMicrosigaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ArrayList_OfficialsMicrosigaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ArrayList_OfficialsMicrosigaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ArrayList_activedirectoryCompletedEventHandler(object sender, ArrayList_activedirectoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ArrayList_activedirectoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ArrayList_activedirectoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void wsSAMAccountNameCompletedEventHandler(object sender, wsSAMAccountNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsSAMAccountNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsSAMAccountNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void wsFullNameCompletedEventHandler(object sender, wsFullNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsFullNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsFullNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void wsDepartmentCompletedEventHandler(object sender, wsDepartmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void wsEmailRequestorCompletedEventHandler(object sender, wsEmailRequestorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsEmailRequestorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsEmailRequestorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void wsCompanyCompletedEventHandler(object sender, wsCompanyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsCompanyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsCompanyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void wsContainerCompletedEventHandler(object sender, wsContainerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsContainerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsContainerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void wsBiometricoCompletedEventHandler(object sender, wsBiometricoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsBiometricoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsBiometricoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void wsAnalistaCompletedEventHandler(object sender, wsAnalistaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsAnalistaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsAnalistaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591